/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as FacultyRouteImport } from './routes/faculty'
import { Route as OfficersRouteImport } from './routes/officers'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminAnnouncementsRouteImport } from './routes/admin.announcements'
import { Route as AdminApprovalsRouteImport } from './routes/admin.approvals'
import { Route as AdminAuditLogsRouteImport } from './routes/admin.audit-logs'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as AdminEventsRouteImport } from './routes/admin.events'
import { Route as AdminFacultyRouteImport } from './routes/admin.faculty'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminMessagesRouteImport } from './routes/admin.messages'
import { Route as AdminOfficersRouteImport } from './routes/admin.officers'
import { Route as AdminPagesRouteImport } from './routes/admin.pages'
import { Route as AdminPasswordRouteImport } from './routes/admin.password'
import { Route as AdminProfileRouteImport } from './routes/admin.profile'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminSubmissionsRouteImport } from './routes/admin.submissions'
import { Route as AdminTransparencyRouteImport } from './routes/admin.transparency'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AnnouncementsIndexRouteImport } from './routes/announcements.index'
import { Route as AnnouncementsSlugRouteImport } from './routes/announcements.$slug'
import { Route as EventsIndexRouteImport } from './routes/events.index'
import { Route as EventsSlugRouteImport } from './routes/events.$slug'
import { Route as TransparencyIndexRouteImport } from './routes/transparency.index'
import { Route as TransparencySlugRouteImport } from './routes/transparency.$slug'
import { Route as ApiPublicLogoRouteImport } from './routes/api/public/logo'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const FacultyRoute = FacultyRouteImport.update({
  id: '/faculty',
  path: '/faculty',
  getParentRoute: () => rootRouteImport,
} as any)
const OfficersRoute = OfficersRouteImport.update({
  id: '/officers',
  path: '/officers',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAnnouncementsRoute = AdminAnnouncementsRouteImport.update({
  id: '/admin/announcements',
  path: '/admin/announcements',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminApprovalsRoute = AdminApprovalsRouteImport.update({
  id: '/admin/approvals',
  path: '/admin/approvals',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuditLogsRoute = AdminAuditLogsRouteImport.update({
  id: '/admin/audit-logs',
  path: '/admin/audit-logs',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEventsRoute = AdminEventsRouteImport.update({
  id: '/admin/events',
  path: '/admin/events',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminFacultyRoute = AdminFacultyRouteImport.update({
  id: '/admin/faculty',
  path: '/admin/faculty',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMessagesRoute = AdminMessagesRouteImport.update({
  id: '/admin/messages',
  path: '/admin/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOfficersRoute = AdminOfficersRouteImport.update({
  id: '/admin/officers',
  path: '/admin/officers',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPagesRoute = AdminPagesRouteImport.update({
  id: '/admin/pages',
  path: '/admin/pages',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPasswordRoute = AdminPasswordRouteImport.update({
  id: '/admin/password',
  path: '/admin/password',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProfileRoute = AdminProfileRouteImport.update({
  id: '/admin/profile',
  path: '/admin/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSubmissionsRoute = AdminSubmissionsRouteImport.update({
  id: '/admin/submissions',
  path: '/admin/submissions',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTransparencyRoute = AdminTransparencyRouteImport.update({
  id: '/admin/transparency',
  path: '/admin/transparency',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AnnouncementsIndexRoute = AnnouncementsIndexRouteImport.update({
  id: '/announcements/',
  path: '/announcements/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnnouncementsSlugRoute = AnnouncementsSlugRouteImport.update({
  id: '/announcements/$slug',
  path: '/announcements/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsIndexRoute = EventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsSlugRoute = EventsSlugRouteImport.update({
  id: '/events/$slug',
  path: '/events/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const TransparencyIndexRoute = TransparencyIndexRouteImport.update({
  id: '/transparency/',
  path: '/transparency/',
  getParentRoute: () => rootRouteImport,
} as any)
const TransparencySlugRoute = TransparencySlugRouteImport.update({
  id: '/transparency/$slug',
  path: '/transparency/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicLogoRoute = ApiPublicLogoRouteImport.update({
  id: '/api/public/logo',
  path: '/api/public/logo',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/faculty': typeof FacultyRoute
  '/officers': typeof OfficersRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/announcements': typeof AdminAnnouncementsRoute
  '/admin/approvals': typeof AdminApprovalsRoute
  '/admin/audit-logs': typeof AdminAuditLogsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/faculty': typeof AdminFacultyRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/officers': typeof AdminOfficersRoute
  '/admin/pages': typeof AdminPagesRoute
  '/admin/password': typeof AdminPasswordRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/submissions': typeof AdminSubmissionsRoute
  '/admin/transparency': typeof AdminTransparencyRoute
  '/admin/users': typeof AdminUsersRoute
  '/announcements/$slug': typeof AnnouncementsSlugRoute
  '/events/$slug': typeof EventsSlugRoute
  '/transparency/$slug': typeof TransparencySlugRoute
  '/admin/': typeof AdminIndexRoute
  '/announcements/': typeof AnnouncementsIndexRoute
  '/events/': typeof EventsIndexRoute
  '/transparency/': typeof TransparencyIndexRoute
  '/api/public/logo': typeof ApiPublicLogoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/faculty': typeof FacultyRoute
  '/officers': typeof OfficersRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/announcements': typeof AdminAnnouncementsRoute
  '/admin/approvals': typeof AdminApprovalsRoute
  '/admin/audit-logs': typeof AdminAuditLogsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/faculty': typeof AdminFacultyRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/officers': typeof AdminOfficersRoute
  '/admin/pages': typeof AdminPagesRoute
  '/admin/password': typeof AdminPasswordRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/submissions': typeof AdminSubmissionsRoute
  '/admin/transparency': typeof AdminTransparencyRoute
  '/admin/users': typeof AdminUsersRoute
  '/announcements/$slug': typeof AnnouncementsSlugRoute
  '/events/$slug': typeof EventsSlugRoute
  '/transparency/$slug': typeof TransparencySlugRoute
  '/admin': typeof AdminIndexRoute
  '/announcements': typeof AnnouncementsIndexRoute
  '/events': typeof EventsIndexRoute
  '/transparency': typeof TransparencyIndexRoute
  '/api/public/logo': typeof ApiPublicLogoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/faculty': typeof FacultyRoute
  '/officers': typeof OfficersRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/announcements': typeof AdminAnnouncementsRoute
  '/admin/approvals': typeof AdminApprovalsRoute
  '/admin/audit-logs': typeof AdminAuditLogsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/faculty': typeof AdminFacultyRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/officers': typeof AdminOfficersRoute
  '/admin/pages': typeof AdminPagesRoute
  '/admin/password': typeof AdminPasswordRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/submissions': typeof AdminSubmissionsRoute
  '/admin/transparency': typeof AdminTransparencyRoute
  '/admin/users': typeof AdminUsersRoute
  '/announcements/$slug': typeof AnnouncementsSlugRoute
  '/events/$slug': typeof EventsSlugRoute
  '/transparency/$slug': typeof TransparencySlugRoute
  '/admin/': typeof AdminIndexRoute
  '/announcements/': typeof AnnouncementsIndexRoute
  '/events/': typeof EventsIndexRoute
  '/transparency/': typeof TransparencyIndexRoute
  '/api/public/logo': typeof ApiPublicLogoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/faculty'
    | '/officers'
    | '/sitemap.xml'
    | '/admin/announcements'
    | '/admin/approvals'
    | '/admin/audit-logs'
    | '/admin/dashboard'
    | '/admin/events'
    | '/admin/faculty'
    | '/admin/login'
    | '/admin/messages'
    | '/admin/officers'
    | '/admin/pages'
    | '/admin/password'
    | '/admin/profile'
    | '/admin/settings'
    | '/admin/submissions'
    | '/admin/transparency'
    | '/admin/users'
    | '/announcements/$slug'
    | '/events/$slug'
    | '/transparency/$slug'
    | '/admin/'
    | '/announcements/'
    | '/events/'
    | '/transparency/'
    | '/api/public/logo'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/faculty'
    | '/officers'
    | '/sitemap.xml'
    | '/admin/announcements'
    | '/admin/approvals'
    | '/admin/audit-logs'
    | '/admin/dashboard'
    | '/admin/events'
    | '/admin/faculty'
    | '/admin/login'
    | '/admin/messages'
    | '/admin/officers'
    | '/admin/pages'
    | '/admin/password'
    | '/admin/profile'
    | '/admin/settings'
    | '/admin/submissions'
    | '/admin/transparency'
    | '/admin/users'
    | '/announcements/$slug'
    | '/events/$slug'
    | '/transparency/$slug'
    | '/admin'
    | '/announcements'
    | '/events'
    | '/transparency'
    | '/api/public/logo'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/faculty'
    | '/officers'
    | '/sitemap.xml'
    | '/admin/announcements'
    | '/admin/approvals'
    | '/admin/audit-logs'
    | '/admin/dashboard'
    | '/admin/events'
    | '/admin/faculty'
    | '/admin/login'
    | '/admin/messages'
    | '/admin/officers'
    | '/admin/pages'
    | '/admin/password'
    | '/admin/profile'
    | '/admin/settings'
    | '/admin/submissions'
    | '/admin/transparency'
    | '/admin/users'
    | '/announcements/$slug'
    | '/events/$slug'
    | '/transparency/$slug'
    | '/admin/'
    | '/announcements/'
    | '/events/'
    | '/transparency/'
    | '/api/public/logo'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  FacultyRoute: typeof FacultyRoute
  OfficersRoute: typeof OfficersRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  AdminAnnouncementsRoute: typeof AdminAnnouncementsRoute
  AdminApprovalsRoute: typeof AdminApprovalsRoute
  AdminAuditLogsRoute: typeof AdminAuditLogsRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminEventsRoute: typeof AdminEventsRoute
  AdminFacultyRoute: typeof AdminFacultyRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminMessagesRoute: typeof AdminMessagesRoute
  AdminOfficersRoute: typeof AdminOfficersRoute
  AdminPagesRoute: typeof AdminPagesRoute
  AdminPasswordRoute: typeof AdminPasswordRoute
  AdminProfileRoute: typeof AdminProfileRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminSubmissionsRoute: typeof AdminSubmissionsRoute
  AdminTransparencyRoute: typeof AdminTransparencyRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AnnouncementsSlugRoute: typeof AnnouncementsSlugRoute
  EventsSlugRoute: typeof EventsSlugRoute
  TransparencySlugRoute: typeof TransparencySlugRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AnnouncementsIndexRoute: typeof AnnouncementsIndexRoute
  EventsIndexRoute: typeof EventsIndexRoute
  TransparencyIndexRoute: typeof TransparencyIndexRoute
  ApiPublicLogoRoute: typeof ApiPublicLogoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faculty': {
      id: '/faculty'
      path: '/faculty'
      fullPath: '/faculty'
      preLoaderRoute: typeof FacultyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/officers': {
      id: '/officers'
      path: '/officers'
      fullPath: '/officers'
      preLoaderRoute: typeof OfficersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/announcements': {
      id: '/admin/announcements'
      path: '/admin/announcements'
      fullPath: '/admin/announcements'
      preLoaderRoute: typeof AdminAnnouncementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/approvals': {
      id: '/admin/approvals'
      path: '/admin/approvals'
      fullPath: '/admin/approvals'
      preLoaderRoute: typeof AdminApprovalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/audit-logs': {
      id: '/admin/audit-logs'
      path: '/admin/audit-logs'
      fullPath: '/admin/audit-logs'
      preLoaderRoute: typeof AdminAuditLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/events': {
      id: '/admin/events'
      path: '/admin/events'
      fullPath: '/admin/events'
      preLoaderRoute: typeof AdminEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/faculty': {
      id: '/admin/faculty'
      path: '/admin/faculty'
      fullPath: '/admin/faculty'
      preLoaderRoute: typeof AdminFacultyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/messages': {
      id: '/admin/messages'
      path: '/admin/messages'
      fullPath: '/admin/messages'
      preLoaderRoute: typeof AdminMessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/officers': {
      id: '/admin/officers'
      path: '/admin/officers'
      fullPath: '/admin/officers'
      preLoaderRoute: typeof AdminOfficersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/pages': {
      id: '/admin/pages'
      path: '/admin/pages'
      fullPath: '/admin/pages'
      preLoaderRoute: typeof AdminPagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/password': {
      id: '/admin/password'
      path: '/admin/password'
      fullPath: '/admin/password'
      preLoaderRoute: typeof AdminPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/profile': {
      id: '/admin/profile'
      path: '/admin/profile'
      fullPath: '/admin/profile'
      preLoaderRoute: typeof AdminProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/submissions': {
      id: '/admin/submissions'
      path: '/admin/submissions'
      fullPath: '/admin/submissions'
      preLoaderRoute: typeof AdminSubmissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/transparency': {
      id: '/admin/transparency'
      path: '/admin/transparency'
      fullPath: '/admin/transparency'
      preLoaderRoute: typeof AdminTransparencyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/announcements/': {
      id: '/announcements/'
      path: '/announcements'
      fullPath: '/announcements/'
      preLoaderRoute: typeof AnnouncementsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/announcements/$slug': {
      id: '/announcements/$slug'
      path: '/announcements/$slug'
      fullPath: '/announcements/$slug'
      preLoaderRoute: typeof AnnouncementsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/': {
      id: '/events/'
      path: '/events'
      fullPath: '/events/'
      preLoaderRoute: typeof EventsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$slug': {
      id: '/events/$slug'
      path: '/events/$slug'
      fullPath: '/events/$slug'
      preLoaderRoute: typeof EventsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transparency/': {
      id: '/transparency/'
      path: '/transparency'
      fullPath: '/transparency/'
      preLoaderRoute: typeof TransparencyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transparency/$slug': {
      id: '/transparency/$slug'
      path: '/transparency/$slug'
      fullPath: '/transparency/$slug'
      preLoaderRoute: typeof TransparencySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/logo': {
      id: '/api/public/logo'
      path: '/api/public/logo'
      fullPath: '/api/public/logo'
      preLoaderRoute: typeof ApiPublicLogoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  FacultyRoute: FacultyRoute,
  OfficersRoute: OfficersRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  AdminAnnouncementsRoute: AdminAnnouncementsRoute,
  AdminApprovalsRoute: AdminApprovalsRoute,
  AdminAuditLogsRoute: AdminAuditLogsRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminEventsRoute: AdminEventsRoute,
  AdminFacultyRoute: AdminFacultyRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminMessagesRoute: AdminMessagesRoute,
  AdminOfficersRoute: AdminOfficersRoute,
  AdminPagesRoute: AdminPagesRoute,
  AdminPasswordRoute: AdminPasswordRoute,
  AdminProfileRoute: AdminProfileRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminSubmissionsRoute: AdminSubmissionsRoute,
  AdminTransparencyRoute: AdminTransparencyRoute,
  AdminUsersRoute: AdminUsersRoute,
  AnnouncementsSlugRoute: AnnouncementsSlugRoute,
  EventsSlugRoute: EventsSlugRoute,
  TransparencySlugRoute: TransparencySlugRoute,
  AdminIndexRoute: AdminIndexRoute,
  AnnouncementsIndexRoute: AnnouncementsIndexRoute,
  EventsIndexRoute: EventsIndexRoute,
  TransparencyIndexRoute: TransparencyIndexRoute,
  ApiPublicLogoRoute: ApiPublicLogoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
